
global DETECTION_DEBUG;
DETECTION_DEBUG = struct('RGB_debug', false, ...
                         'dilation_erosion_debug', false, ...
                         'vertical_lines_debug', false, ...
                         'horizontal_lines_debug', false, ...
                         'resulting_lines_debug', false, ...
                         'extracted_corners_debug', false, ...
                         'resulting_corners_debug', false);

global DILATION_DISK_SIZE;
DILATION_DISK_SIZE = 2;
                     
% PARAMETERS SMALL PENCIL                     
% 
%                                  
% global HOUGH_PARAMS_HORIZONTAL_LINES;
% 
% HOUGH_PARAMS_HORIZONTAL_LINES = struct('theta_rotated_image', -40:1:40, ...
%                                         'rho_resolution', 2, ...
%                                         'peacks_number', 10, ...
%                                         'nhood_size_scale', 50, ...
%                                         'fill_gap', 20, ...
%                                         'min_length', 30, ...
%                                         'threshold_mult', 0);
                                    
global HOUGH_PARAMS_VERTICAL_LINES;
HOUGH_PARAMS_VERTICAL_LINES = struct('theta', -80:1:80, ...
                                     'rho_resolution', 2, ...
                                     'peacks_number', 20, ...
                                     'nhood_size_scale', 200, ...
                                     'fill_gap',100, ...
                                     'min_length', 200, ...
                                     'threshold_mult', 0.5);

% parameters di ciao corsivo
HOUGH_PARAMS_HORIZONTAL_LINES = struct('theta_rotated_image', 0:1:80, ...
                                       'rho_resolution', 2, ...
                                       'peacks_number', 10, ...
                                       'nhood_size_scale', 50, ...
                                       'fill_gap', 20, ...
                                       'min_length', 30, ...
                                       'threshold_mult', 0);

global RGB_FILTER_FUNCTION;
RGB_FILTER_FUNCTION = @(x) createMask_ciaocorsivo1(x) | createMask_ciaocorsivo2(x) | createMask_ciaocorsivo3(x);                                   

global HARRIS_QUALITY;
HARRIS_QUALITY = 0.05;

global HARRIS_ROI_SIZE;
HARRIS_ROI_SIZE = 15;
                                   
global GEO_2D_CHECK_THRESHOLD;
GEO_2D_CHECK_THRESHOLD = 2^2; % pixels



