
global PENCIL_MODEL;

% APPLE PENCIL
% marker_model = struct('high_med_distance', 3.4, ... 
%                       'med_low_distance', 3.4, ... 
%                       'horiz_distance', 0.5);
% 
% PENCIL_MODEL = struct('marker_model', marker_model, ...
%                       'marker_low_brush_distance', 8.5, ...
%                       'depth_distance', 0.5);
              
% SMALL PEN
% 
% marker_model = struct('high_med_distance', 2.9, ... 
%                       'med_low_distance', 2.9, ... 
%                       'horiz_distance', 0.4);
% 
% PENCIL_MODEL = struct('marker_model', marker_model, ...
%                       'marker_low_brush_distance', 7.5, ...
%                       'depth_distance', 0.5);

              
% %NEW PEN

marker_model = struct('high_med_distance', 3.45, ... 
                      'med_low_distance', 3.45, ... 
                      'horiz_distance', 0.45);

PENCIL_MODEL = struct('marker_model', marker_model, ...
                      'marker_low_brush_distance', 7.6, ...
                      'depth_distance', 0.);